### ISSUE TITLE
ENOENT: no such file or directory, open '.secret'

### ISSUE THREAD

**Issue by MaitreyPrajapati** [loevda/supplyChainDApp#1]
Having trouble while compiling the contracts

`Error: ENOENT: no such file or directory, open '.secret'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/Users/Maitrey/Desktop/Solulab/Hyperledger/ethereum/gsiw/supplyChainDApp/truffle-config.js:10:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Function.Config.load (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:381:1)
    at Function.Config.detect (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:370:1)
    at Object.run (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/compile.js:56:1)
    at Command.run (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:54:1)
    at __webpack_require__ (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 69e30829cd47ee94a967:19:1)
    at /Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 69e30829cd47ee94a967:65:1
    at Object.<anonymous> (/Users/Maitrey/.nvm/versions/node/v8.15.1/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Truffle v5.0.4 (core: 5.0.4)
Node v8.15.1
`

**Comment by loevda** [comment]
You need to create an hidden file named ".secret" inside the root directory. Inside this file just paste in it your private key seed.

**Comment by mando-dev** [comment]
After I put the private key and secret file on root of project, I got this error: 
![Screen Shot 2022-01-12 at 9 56 19 PM](https://user-images.githubusercontent.com/76628348/149144491-f1decbae-96c5-4b53-80d5-519b8026cb13.png)

Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: mumbai - private key too long, expected 32 bytes
  * Invalid account: #0 for network: mainnet - private key too long, expected 32 bytes
  
To learn more about Hardhat's configuration, please go to https://hardhat.org/config/
